### ISSUE TITLE
Extension needs a license (publish to inkscape.org)

### ISSUE THREAD

**Issue by Moini** [Klowner/inkscape-applytransforms#1]
Hi Klowner,

could you add a license to the extension? It's a useful tool for many people, but it's currently not 'safe to use'. I would suggest 'GPLv2 or higher', for it to be compatible with Inkscape's licensing.

**Comment by Klowner** [comment]
Sure! How's this?

**Comment by Moini** [comment]
Wow, that was fast! Thank you! :D

**Comment by Moini** [comment]
Would you like to publish the extension (or a link to it) at inkscape.org? 
Here's what it would look like there: https://inkscape.org/en/download/addons/, upload instructions can be found here: https://inkscape.org/en/develop/extensions/#sharing-your-extension

**Comment by Klowner** [comment]
Ya I can do that, it'll take me a little longer since I'll need to make a thumbnail and stuff :+1:

**Comment by Moini** [comment]
It's great to see the extensions gallery growing - no matter how long it takes ;-) 
(I've recommended this extension quite a few times, there is a demand for it!)

Can you make a note there that it will turn a couple of objects to paths (stars, LPEs, ...) and will move clones to the position of their original?

I think it's most useful for people who want to do plotting of some sort, at least that's why people came and asked for the functionality in the forums (I haven't had the chance to try to plot or cut anything yet, unfortunately).

**Comment by Klowner** [comment]
Did a little clean-up and fixed the selected-only operation, figured that would be nice to have working.

Not sure what I can show for a thumbnail, considering this extension does behind-the-scenes work mostly.

**Comment by Moini** [comment]
I agree it's difficult to find an image for this one. Mmmh.... how about a dissolving matrix ;-) ?

**Comment by Klowner** [comment]
before: Keanu
after: No Keanu

**Comment by Klowner** [comment]
http://imgur.com/a/jBVzd ? 💃

**Comment by Moini** [comment]
No matrices allowed beyond this point... Why not :D

**Comment by Moini** [comment]
(only make sure the matrix is free to be used... like this one: 
https://openclipart.org/detail/248382/dropping-numbers (I admit it's less cool))

**Comment by Klowner** [comment]
haha, works for me

**Comment by Klowner** [comment]
https://inkscape.org/en/~Klowner/%E2%98%85apply-transforms 👍

**Comment by Moini** [comment]
Thanks! :D

**Comment by Klowner** [comment]
You bet, thank you!
