### ISSUE TITLE
Does not remove all scale transformations

### ISSUE THREAD

**Issue by gromgull** [Klowner/inkscape-applytransforms#10]
I flipped some objects with `Edit->Flip Horizonal/Vertical` (or hitting v or h) 

After running the plugin, the source is still left with: `transform="scale(-1,1)"`

Maybe this is the desired behaviour, it wasn't for me :)

Thanks for an otherwise very useful plugin!

**Comment by Klowner** [comment]
Yeah that doesn't seem right

**Comment by ziegenberg** [comment]
Hi @gromgull, can you provide some examples?

**Comment by vmario89** [comment]
this can be closed too. applying scales and work properly

**Comment by Klowner** [comment]
thank you, @vmario89!
