### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by imabot2** [Klowner/inkscape-applytransforms#17]
Extension does not work with my last Inkscape version. The following error is displayed : 

```
  File "applytransform.py", line 1
    <?xml version="1.0" encoding="UTF-8"?>
    ^
SyntaxError: invalid syntax
```
Ubuntu 18.04
Inkscape 0.92.3 (2405546, 2018-03-11)

**Comment by Klowner** [comment]
Sounds like maybe you saved `applytransforms.inx` as `applytransforms.py`? The first line of `applytransforms.py` should be `#!/usr/bin/env python2` not the xml tag.

**Comment by Klowner** [comment]
Feel free to re-open if you're still having an issue

**Comment by imabot2** [comment]
You are right, I copied the content of applytransform.inx in both files applytransform.inx and applytransform.py. 

Thank you for your help.
