### ISSUE TITLE
`circle` elements don't get transformed

### ISSUE THREAD

**Issue by SebKuzminsky** [Klowner/inkscape-applytransforms#19]
Here's the original SVG (with `.txt` extension added so github accepts it...):
[plate.svg.txt](https://github.com/Klowner/inkscape-applytransforms/files/3318757/plate.svg.txt)

The original SVG rendered as PNG: 
![plate](https://user-images.githubusercontent.com/400548/59984166-6a4ca200-95e4-11e9-8ebf-a954a379b51e.png) 

SVG with "Apply Transform" run, rendered as PNG:
![plate-transformed](https://user-images.githubusercontent.com/400548/59984179-8f411500-95e4-11e9-8537-f6fedf0e3ec6.png)

And finally, the transformed SVG: 
[plate-transformed.svg.txt](https://github.com/Klowner/inkscape-applytransforms/files/3318758/plate-transformed.svg.txt)

It looks like the outline had the transformation applied, but the circles did not.

**Comment by Klowner** [comment]
Thank you for the very good bug report, I'll give this a look.

**Comment by Klowner** [comment]
@SebKuzminsky I'm pretty sure you should be good to go :+1:

**Comment by SebKuzminsky** [comment]
The transformed `<circle>` elements still have `transform` attributes:
~~~
    <circle
       transform="matrix(1.000000,0.000000,0.000000,-1.000000,0.000000,0.000000)"
       id="circle9"
       style="stroke-dasharray:none;stroke-width:0.13096206843;stroke-miterlimit:4;fill:none"
       stroke-width="0.35 px"
       stroke="#000000"
       r="3.3782"
       cy="-27.7016123259"
       cx="47.9806" />
~~~

I'd expect the `circle` elements to have the transform applied and not have a "residual" `transform` attribute, just like what's done to the `path` element.

**Comment by Klowner** [comment]
Whoops, you are correct

**Comment by Klowner** [comment]
I see, it actually *adds* transform matrices..  that ain't right

**Comment by ziegenberg** [comment]
Testing with the provided original SVG and comparing with the output from this extension it looked like this is fixed now.

**Comment by vmario89** [comment]
jup. please close this issue
