### ISSUE TITLE
Issue in the last commit made at Oct 19, 2019 

### ISSUE THREAD

**Issue by kosilin** [Klowner/inkscape-applytransforms#22]
Good day!

The last commit at Oct 19, 2019 has introduced a new issue. Please look at the line 55 (as it seems) of the script:
    stroke_width *= math.sqrt(transf[0][0] * transf[1][1])

This code will cause a domain error while scaling stroke width in case the figure being transformed has been previously flipped (mirrored) around one of the axises.

I propose to correct the problem by getting absolute value of the multiplication:
   stroke_width *= math.sqrt(abs(transf[0][0] * transf[1][1]))

Best regards,
Alexey

**Comment by Klowner** [comment]
Thanks!
