### ISSUE TITLE
fails to load

### ISSUE THREAD

**Issue by bad-blue-bull** [Klowner/inkscape-applytransforms#27]
Inkscape 0.92, GNU/Linux
`
/home/nr/.config/inkscape/extensions/applytransform.inx:46: parser error : Specification mandate value for attribute data-pjax-transient
a name="hovercard-subject-tag" content="repository:15256624" data-pjax-transient
                                                                               ^
/home/nr/.config/inkscape/extensions/applytransform.inx:53: parser error : Specification mandate value for attribute data-pjax-transient
  <meta name="selected-link" value="repo_source" data-pjax-transient>
                                                                    ^
/home/nr/.config/inkscape/extensions/applytransform.inx:68: parser error : Specification mandate value for attribute data-pjax-transient
ta class="js-ga-set" name="dimension10" content="Responsive" data-pjax-transient
                                                                               ^
/home/nr/.config/inkscape/extensions/applytransform.inx:95: parser error : Specification mandate value for attribute data-pjax-transient
ner/inkscape-applytransforms/blob/master/applytransform.inx" data-pjax-transient
                                                                               ^
/home/nr/.config/inkscape/extensions/applytransform.inx:111: parser error : Opening and ending tag mismatch: link line 109 and head
  </head>
         ^
/home/nr/.config/inkscape/extensions/applytransform.inx:144: parser error : Entity 'nbsp' not defined
                Sign&nbsp;up
                          ^
/home/nr/.config/inkscape/extensions/applytransform.inx:171: parser error : Entity 'rarr' not defined
es <span class="Bump-link-symbol float-right text-normal text-gray-light">&rarr;
                                                                               ^
/home/nr/.config/inkscape/extensions/applytransform.inx:184: parser error : Entity 'rarr' not defined
es <span class="Bump-link-symbol float-right text-normal text-gray-light">&rarr;
                                                                               ^
/home/nr/.config/inkscape/extensions/applytransform.inx:185: parser error : Entity 'rarr' not defined
ty <span class="Bump-link-symbol float-right text-normal text-gray-light">&rarr;
                                                                               ^
/home/nr/.config/inkscape/extensions/applytransform.inx:208: parser error : Entity 'rarr' not defined
ub <span class="Bump-link-symbol float-right text-normal text-gray-light">&rarr;
                                                                               ^
/home/nr/.config/inkscape/extensions/applytransform.inx:244: parser error : Entity 'rarr' not defined
ns <span class="Bump-link-symbol float-right text-normal text-gray-light">&rarr;
                                                                               ^
/home/nr/.config/inkscape/extensions/applytransform.inx:252: parser error : Entity 'rarr' not defined
it <span class="Bump-link-symbol float-right text-normal text-gray-light">&rarr;
                                                                               ^
/home/nr/.config/inkscape/extensions/applytransform.inx:253: parser error : Entity 'rarr' not defined
on <span class="Bump-link-symbol float-right text-normal text-gray-light">&rarr;
                                                                               ^
/home/nr/.config/inkscape/extensions/applytransform.inx:271: parser error : Opening and ending tag mismatch: div line 270 and option
    </option></form><form class="js-site-s
                                                   ^
/home/nr/.config/inkscape/extensions/applytransform.inx:271: parser error : Opening and ending tag mismatch: div line 263 and form
    </option></form><form class="js-site-s
                                                          ^
/home/nr/.config/inkscape/extensions/applytransform.inx:325: parser error : Opening and ending tag mismatch: img line 306 and a
  </a>
      ^
/home/nr/.config/inkscape/extensions/applytransform.inx:326: parser error : Opening and ending tag mismatch: a line 299 and li
</li>
     ^
/home/nr/.config/inkscape/extensions/applytransform.inx:328: parser error : Opening and ending tag mismatch: li line 298 and ul
</ul>
     ^
/home/nr/.config/inkscape/extensions/applytransform.inx:366: parser error : Opening and ending tag mismatch: img line 347 and a
  </a>
      ^
/home/nr/.config/inkscape/extensions/applytransform.inx:367: parser error : Opening and ending tag mismatch: a line 340 and li
</li>
     ^
/home/nr/.config/inkscape/extensions/applytransform.inx:398: parser error : Opening and ending tag mismatch: img line 379 and a
  </a>
      ^
/home/nr/.config/inkscape/extensions/applytransform.inx:399: parser error : Opening and ending tag mismatch: a line 372 and li
</li>
     ^
/home/nr/.config/inkscape/extensions/applytransform.inx:402: parser error : Opening and ending tag mismatch: li line 371 and ul
</ul>
     ^
/home/nr/.config/inkscape/extensions/applytransform.inx:404: parser error : Opening and ending tag mismatch: li line 339 and div
            </div>
                  ^
/home/nr/.config/inkscape/extensions/applytransform.inx:405: parser error : Opening and ending tag mismatch: ul line 336 and label
      </label>
              ^
/home/nr/.config/inkscape/extensions/applytransform.inx:406: parser error : Opening and ending tag mismatch: ul line 295 and form
</form>  </div>
       ^
/home/nr/.config/inkscape/extensions/applytransform.inx:407: parser error : Opening and ending tag mismatch: img line 291 and div
</div>
      ^
/home/nr/.config/inkscape/extensions/applytransform.inx:409: parser error : Opening and ending tag mismatch: input line 290 and div
          </div>
                ^
/home/nr/.config/inkscape/extensions/applytransform.inx:415: parser error : Entity 'nbsp' not defined
          Sign&nbsp;in
                    ^
/home/nr/.config/inkscape/extensions/applytransform.inx:421: parser error : Entity 'nbsp' not defined
              Sign&nbsp;up
                        ^
/home/nr/.config/inkscape/extensions/applytransform.inx:423: parser error : Opening and ending tag mismatch: label line 272 and div
      </div>
            ^
/home/nr/.config/inkscape/extensions/applytransform.inx:424: parser error : Opening and ending tag mismatch: form line 271 and div
    </div>
          ^
/home/nr/.config/inkscape/extensions/applytransform.inx:426: parser error : Opening and ending tag mismatch: div line 261 and header
</header>
         ^
/home/nr/.config/inkscape/extensions/applytransform.inx:462: parser error : Specification mandate value for attribute data-commit-hovercards-enabled
    data-discussion-hovercards-enabled
    ^
/home/nr/.config/inkscape/extensions/applytransform.inx:462: parser error : attributes construct error
    data-discussion-hovercards-enabled
    ^
/home/nr/.config/inkscape/extensions/applytransform.inx:462: parser error : Couldn't find end of Start Tag div line 459
    data-discussion-hovercards-enabled
    ^
/home/nr/.config/inkscape/extensions/applytransform.inx:465: parser error : Specification mandate value for attribute itemscope
        <div itemscope itemtype="http://schema.org/SoftwareSourceCode" class="">
                       ^
/home/nr/.config/inkscape/extensions/applytransform.inx:465: parser error : attributes construct error
        <div itemscope itemtype="http://schema.org/SoftwareSourceCode" class="">
                       ^
/home/nr/.config/inkscape/extensions/applytransform.inx:465: parser error : Couldn't find end of Start Tag div line 465
        <div itemscope itemtype="http://schema.org/SoftwareSourceCode" class="">
                       ^
/home/nr/.config/inkscape/extensions/applytransform.inx:614: parser error : Specification mandate value for attribute hidden
                <li data-menu-item="code-tab" hidden>
                                                    ^
/home/nr/.config/inkscape/extensions/applytransform.inx:618: parser error : Specification mandate value for attribute hidden
                <li data-menu-item="issues-tab" hidden>
                                                      ^
/home/nr/.config/inkscape/extensions/applytransform.inx:622: parser error : Specification mandate value for attribute hidden
                <li data-menu-item="pull-requests-tab" hidden>
                                                             ^
/home/nr/.config/inkscape/extensions/applytransform.inx:626: parser error : Specification mandate value for attribute hidden
                <li data-menu-item="actions-tab" hidden>
                                                       ^
/home/nr/.config/inkscape/extensions/applytransform.inx:630: parser error : Specification mandate value for attribute hidden
                <li data-menu-item="projects-tab" hidden>
                                                        ^
/home/nr/.config/inkscape/extensions/applytransform.inx:634: parser error : Specification mandate value for attribute hidden
                <li data-menu-item="security-tab" hidden>
                                                        ^
/home/nr/.config/inkscape/extensions/applytransform.inx:638: parser error : Specification mandate value for attribute hidden
                <li data-menu-item="insights-tab" hidden>
                                                        ^
/home/nr/.config/inkscape/extensions/applytransform.inx:665: parser error : Specification mandate value for attribute hidden
   <signup-prompt class="signup-prompt-bg rounded-1" data-prompt="signup" hidden
                                                                               ^
/home/nr/.config/inkscape/extensions/applytransform.inx:693: parser error : Specification mandate value for attribute data-menu-button
    <span class="css-truncate-target" data-menu-button>master</span>
                                                      ^
/home/nr/.config/inkscape/extensions/applytransform.inx:697: parser error : Specification mandate value for attribute preload
master/applytransform.inx?source_action=show&amp;source_controller=blob" preload
                                                                               ^
/home/nr/.config/inkscape/extensions/applytransform.inx:712: parser error : Specification mandate value for attribute data-pjax
              data-hotkey="t">
              ^
/home/nr/.config/inkscape/extensions/applytransform.inx:712: parser error : attributes construct error
              data-hotkey="t">
              ^
/home/nr/.config/inkscape/extensions/applytransform.inx:712: parser error : Couldn't find end of Start Tag a line 709
              data-hotkey="t">
              ^
/home/nr/.config/inkscape/extensions/applytransform.inx:714: parser error : Opening and ending tag mismatch: div line 684 and a
        </a>
            ^
/home/nr/.config/inkscape/extensions/applytransform.inx:755: parser error : Entity 'nbsp' not defined
            <div class="Skeleton Skeleton--text col-5 ml-2">&nbsp;</div>
                                                                  ^
/home/nr/.config/inkscape/extensions/applytransform.inx:759: parser error : Entity 'nbsp' not defined
            <div class="Skeleton Skeleton--text col-1">&nbsp;</div>
                                                             ^
/home/nr/.config/inkscape/extensions/applytransform.inx:815: parser error : Specification mandate value for attribute data-paste-markdown-skip
ight tab-size js-file-line-container" data-tab-size="8" data-paste-markdown-skip
                                                                               ^
/home/nr/.config/inkscape/extensions/applytransform.inx:926: parser error : Opening and ending tag mismatch: details-dialog line 925 and option
      </option></form><form class="js-jump
                                                     ^
/home/nr/.config/inkscape/extensions/applytransform.inx:926: parser error : Opening and ending tag mismatch: details line 923 and form
      </option></form><form class="js-jump
                                                            ^
/home/nr/.config/inkscape/extensions/applytransform.inx:927: parser error : Entity 'hellip' not defined
ejump-input js-jump-to-line-field" type="text" placeholder="Jump to line&hellip;
                                                                               ^
/home/nr/.config/inkscape/extensions/applytransform.inx:927: parser error : Specification mandate value for attribute autofocus
pe="text" placeholder="Jump to line&hellip;" aria-label="Jump to line" autofocus
                                                                               ^
/home/nr/.config/inkscape/extensions/applytransform.inx:928: parser error : Specification mandate value for attribute data-close-dialog
        <button type="submit" class="btn" data-close-dialog>Go</button>
                                                           ^
/home/nr/.config/inkscape/extensions/applytransform.inx:929: parser error : Opening and ending tag mismatch: input line 927 and form
</form>    </details-dialog>
       ^
/home/nr/.config/inkscape/extensions/applytransform.inx:929: parser error : Opening and ending tag mismatch: form line 926 and details-dialog
</form>    </details-dialog>
                            ^
/home/nr/.config/inkscape/extensions/applytransform.inx:930: parser error : Opening and ending tag mismatch: div line 653 and details
  </details>
            ^
/home/nr/.config/inkscape/extensions/applytransform.inx:935: parser error : Opening and ending tag mismatch: main line 466 and div
  </div>
        ^
/home/nr/.config/inkscape/extensions/applytransform.inx:938: parser error : Opening and ending tag mismatch: header line 127 and main
    </main>
           ^
/home/nr/.config/inkscape/extensions/applytransform.inx:942: parser error : Opening and ending tag mismatch: body line 113 and div
  </div>
        ^
/home/nr/.config/inkscape/extensions/applytransform.inx:948: parser error : Entity 'copy' not defined
      <li class="mr-3 mr-lg-0">&copy; 2020 GitHub, Inc.</li>
                                     ^
/home/nr/.config/inkscape/extensions/applytransform.inx:998: parser error : Specification mandate value for attribute hidden
    >
    ^
/home/nr/.config/inkscape/extensions/applytransform.inx:1000: parser error : Specification mandate value for attribute hidden
    <span class="js-stale-session-flash-signed-in" hidden>You signed in with ano
                                                         ^
/home/nr/.config/inkscape/extensions/applytransform.inx:1001: parser error : Specification mandate value for attribute hidden
    <span class="js-stale-session-flash-signed-out" hidden>You signed out in ano
                                                          ^
/home/nr/.config/inkscape/extensions/applytransform.inx:1004: parser error : Specification mandate value for attribute open
eset details-overlay details-overlay-dark lh-default text-gray-dark hx_rsm" open
                                                                               ^
/home/nr/.config/inkscape/extensions/applytransform.inx:1007: parser error : Specification mandate value for attribute data-close-dialog
bsolute right-0 top-0" type="button" aria-label="Close dialog" data-close-dialog
                                                                               ^
/home/nr/.config/inkscape/extensions/applytransform.inx:1021: parser error : Opening and ending tag mismatch: meta line 106 and body
  </body>
         ^
/home/nr/.config/inkscape/extensions/applytransform.inx:1022: parser error : Opening and ending tag mismatch: link line 104 and html
</html>
       ^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 103

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 102

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 100

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 98

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 95

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 90

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 88

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 85

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 83

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 80

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 77

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 76

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 70

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 68

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 65

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 58

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 57

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 56

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 55

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 53

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 46

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 41

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 36

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 35

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 34

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 33

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 32

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 29

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 16

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 15

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 14

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 13

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 12

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 11

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 10

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 9

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag head line 8

^
/home/nr/.config/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag html line 7

^

** (inkscape:10033): WARNING **: Extension definition started with <extension:html> instead of <extension:inkscape-extension>.  Extension will not be created. See http://wiki.inkscape.org/wiki/index.php/Extensions for reference.

** (inkscape:10033): WARNING **: Unable to create extension from definition file /home/nr/.config/inkscape/extensions/applytransform.inx.

/usr/share/inkscape/extensions/applytransform.inx:46: parser error : Specification mandate value for attribute data-pjax-transient
a name="hovercard-subject-tag" content="repository:15256624" data-pjax-transient
                                                                               ^
/usr/share/inkscape/extensions/applytransform.inx:53: parser error : Specification mandate value for attribute data-pjax-transient
  <meta name="selected-link" value="repo_source" data-pjax-transient>
                                                                    ^
/usr/share/inkscape/extensions/applytransform.inx:68: parser error : Specification mandate value for attribute data-pjax-transient
ta class="js-ga-set" name="dimension10" content="Responsive" data-pjax-transient
                                                                               ^
/usr/share/inkscape/extensions/applytransform.inx:95: parser error : Specification mandate value for attribute data-pjax-transient
ner/inkscape-applytransforms/blob/master/applytransform.inx" data-pjax-transient
                                                                               ^
/usr/share/inkscape/extensions/applytransform.inx:111: parser error : Opening and ending tag mismatch: link line 109 and head
  </head>
         ^
/usr/share/inkscape/extensions/applytransform.inx:144: parser error : Entity 'nbsp' not defined
                Sign&nbsp;up
                          ^
/usr/share/inkscape/extensions/applytransform.inx:171: parser error : Entity 'rarr' not defined
es <span class="Bump-link-symbol float-right text-normal text-gray-light">&rarr;
                                                                               ^
/usr/share/inkscape/extensions/applytransform.inx:184: parser error : Entity 'rarr' not defined
es <span class="Bump-link-symbol float-right text-normal text-gray-light">&rarr;
                                                                               ^
/usr/share/inkscape/extensions/applytransform.inx:185: parser error : Entity 'rarr' not defined
ty <span class="Bump-link-symbol float-right text-normal text-gray-light">&rarr;
                                                                               ^
/usr/share/inkscape/extensions/applytransform.inx:208: parser error : Entity 'rarr' not defined
ub <span class="Bump-link-symbol float-right text-normal text-gray-light">&rarr;
                                                                               ^
/usr/share/inkscape/extensions/applytransform.inx:244: parser error : Entity 'rarr' not defined
ns <span class="Bump-link-symbol float-right text-normal text-gray-light">&rarr;
                                                                               ^
/usr/share/inkscape/extensions/applytransform.inx:252: parser error : Entity 'rarr' not defined
it <span class="Bump-link-symbol float-right text-normal text-gray-light">&rarr;
                                                                               ^
/usr/share/inkscape/extensions/applytransform.inx:253: parser error : Entity 'rarr' not defined
on <span class="Bump-link-symbol float-right text-normal text-gray-light">&rarr;
                                                                               ^
/usr/share/inkscape/extensions/applytransform.inx:271: parser error : Opening and ending tag mismatch: div line 270 and option
    </option></form><form class="js-site-s
                                                   ^
/usr/share/inkscape/extensions/applytransform.inx:271: parser error : Opening and ending tag mismatch: div line 263 and form
    </option></form><form class="js-site-s
                                                          ^
/usr/share/inkscape/extensions/applytransform.inx:325: parser error : Opening and ending tag mismatch: img line 306 and a
  </a>
      ^
/usr/share/inkscape/extensions/applytransform.inx:326: parser error : Opening and ending tag mismatch: a line 299 and li
</li>
     ^
/usr/share/inkscape/extensions/applytransform.inx:328: parser error : Opening and ending tag mismatch: li line 298 and ul
</ul>
     ^
/usr/share/inkscape/extensions/applytransform.inx:366: parser error : Opening and ending tag mismatch: img line 347 and a
  </a>
      ^
/usr/share/inkscape/extensions/applytransform.inx:367: parser error : Opening and ending tag mismatch: a line 340 and li
</li>
     ^
/usr/share/inkscape/extensions/applytransform.inx:398: parser error : Opening and ending tag mismatch: img line 379 and a
  </a>
      ^
/usr/share/inkscape/extensions/applytransform.inx:399: parser error : Opening and ending tag mismatch: a line 372 and li
</li>
     ^
/usr/share/inkscape/extensions/applytransform.inx:402: parser error : Opening and ending tag mismatch: li line 371 and ul
</ul>
     ^
/usr/share/inkscape/extensions/applytransform.inx:404: parser error : Opening and ending tag mismatch: li line 339 and div
            </div>
                  ^
/usr/share/inkscape/extensions/applytransform.inx:405: parser error : Opening and ending tag mismatch: ul line 336 and label
      </label>
              ^
/usr/share/inkscape/extensions/applytransform.inx:406: parser error : Opening and ending tag mismatch: ul line 295 and form
</form>  </div>
       ^
/usr/share/inkscape/extensions/applytransform.inx:407: parser error : Opening and ending tag mismatch: img line 291 and div
</div>
      ^
/usr/share/inkscape/extensions/applytransform.inx:409: parser error : Opening and ending tag mismatch: input line 290 and div
          </div>
                ^
/usr/share/inkscape/extensions/applytransform.inx:415: parser error : Entity 'nbsp' not defined
          Sign&nbsp;in
                    ^
/usr/share/inkscape/extensions/applytransform.inx:421: parser error : Entity 'nbsp' not defined
              Sign&nbsp;up
                        ^
/usr/share/inkscape/extensions/applytransform.inx:423: parser error : Opening and ending tag mismatch: label line 272 and div
      </div>
            ^
/usr/share/inkscape/extensions/applytransform.inx:424: parser error : Opening and ending tag mismatch: form line 271 and div
    </div>
          ^
/usr/share/inkscape/extensions/applytransform.inx:426: parser error : Opening and ending tag mismatch: div line 261 and header
</header>
         ^
/usr/share/inkscape/extensions/applytransform.inx:462: parser error : Specification mandate value for attribute data-commit-hovercards-enabled
    data-discussion-hovercards-enabled
    ^
/usr/share/inkscape/extensions/applytransform.inx:462: parser error : attributes construct error
    data-discussion-hovercards-enabled
    ^
/usr/share/inkscape/extensions/applytransform.inx:462: parser error : Couldn't find end of Start Tag div line 459
    data-discussion-hovercards-enabled
    ^
/usr/share/inkscape/extensions/applytransform.inx:465: parser error : Specification mandate value for attribute itemscope
        <div itemscope itemtype="http://schema.org/SoftwareSourceCode" class="">
                       ^
/usr/share/inkscape/extensions/applytransform.inx:465: parser error : attributes construct error
        <div itemscope itemtype="http://schema.org/SoftwareSourceCode" class="">
                       ^
/usr/share/inkscape/extensions/applytransform.inx:465: parser error : Couldn't find end of Start Tag div line 465
        <div itemscope itemtype="http://schema.org/SoftwareSourceCode" class="">
                       ^
/usr/share/inkscape/extensions/applytransform.inx:614: parser error : Specification mandate value for attribute hidden
                <li data-menu-item="code-tab" hidden>
                                                    ^
/usr/share/inkscape/extensions/applytransform.inx:618: parser error : Specification mandate value for attribute hidden
                <li data-menu-item="issues-tab" hidden>
                                                      ^
/usr/share/inkscape/extensions/applytransform.inx:622: parser error : Specification mandate value for attribute hidden
                <li data-menu-item="pull-requests-tab" hidden>
                                                             ^
/usr/share/inkscape/extensions/applytransform.inx:626: parser error : Specification mandate value for attribute hidden
                <li data-menu-item="actions-tab" hidden>
                                                       ^
/usr/share/inkscape/extensions/applytransform.inx:630: parser error : Specification mandate value for attribute hidden
                <li data-menu-item="projects-tab" hidden>
                                                        ^
/usr/share/inkscape/extensions/applytransform.inx:634: parser error : Specification mandate value for attribute hidden
                <li data-menu-item="security-tab" hidden>
                                                        ^
/usr/share/inkscape/extensions/applytransform.inx:638: parser error : Specification mandate value for attribute hidden
                <li data-menu-item="insights-tab" hidden>
                                                        ^
/usr/share/inkscape/extensions/applytransform.inx:665: parser error : Specification mandate value for attribute hidden
   <signup-prompt class="signup-prompt-bg rounded-1" data-prompt="signup" hidden
                                                                               ^
/usr/share/inkscape/extensions/applytransform.inx:693: parser error : Specification mandate value for attribute data-menu-button
    <span class="css-truncate-target" data-menu-button>master</span>
                                                      ^
/usr/share/inkscape/extensions/applytransform.inx:697: parser error : Specification mandate value for attribute preload
master/applytransform.inx?source_action=show&amp;source_controller=blob" preload
                                                                               ^
/usr/share/inkscape/extensions/applytransform.inx:712: parser error : Specification mandate value for attribute data-pjax
              data-hotkey="t">
              ^
/usr/share/inkscape/extensions/applytransform.inx:712: parser error : attributes construct error
              data-hotkey="t">
              ^
/usr/share/inkscape/extensions/applytransform.inx:712: parser error : Couldn't find end of Start Tag a line 709
              data-hotkey="t">
              ^
/usr/share/inkscape/extensions/applytransform.inx:714: parser error : Opening and ending tag mismatch: div line 684 and a
        </a>
            ^
/usr/share/inkscape/extensions/applytransform.inx:755: parser error : Entity 'nbsp' not defined
            <div class="Skeleton Skeleton--text col-5 ml-2">&nbsp;</div>
                                                                  ^
/usr/share/inkscape/extensions/applytransform.inx:759: parser error : Entity 'nbsp' not defined
            <div class="Skeleton Skeleton--text col-1">&nbsp;</div>
                                                             ^
/usr/share/inkscape/extensions/applytransform.inx:815: parser error : Specification mandate value for attribute data-paste-markdown-skip
ight tab-size js-file-line-container" data-tab-size="8" data-paste-markdown-skip
                                                                               ^
/usr/share/inkscape/extensions/applytransform.inx:926: parser error : Opening and ending tag mismatch: details-dialog line 925 and option
      </option></form><form class="js-jump
                                                     ^
/usr/share/inkscape/extensions/applytransform.inx:926: parser error : Opening and ending tag mismatch: details line 923 and form
      </option></form><form class="js-jump
                                                            ^
/usr/share/inkscape/extensions/applytransform.inx:927: parser error : Entity 'hellip' not defined
ejump-input js-jump-to-line-field" type="text" placeholder="Jump to line&hellip;
                                                                               ^
/usr/share/inkscape/extensions/applytransform.inx:927: parser error : Specification mandate value for attribute autofocus
pe="text" placeholder="Jump to line&hellip;" aria-label="Jump to line" autofocus
                                                                               ^
/usr/share/inkscape/extensions/applytransform.inx:928: parser error : Specification mandate value for attribute data-close-dialog
        <button type="submit" class="btn" data-close-dialog>Go</button>
                                                           ^
/usr/share/inkscape/extensions/applytransform.inx:929: parser error : Opening and ending tag mismatch: input line 927 and form
</form>    </details-dialog>
       ^
/usr/share/inkscape/extensions/applytransform.inx:929: parser error : Opening and ending tag mismatch: form line 926 and details-dialog
</form>    </details-dialog>
                            ^
/usr/share/inkscape/extensions/applytransform.inx:930: parser error : Opening and ending tag mismatch: div line 653 and details
  </details>
            ^
/usr/share/inkscape/extensions/applytransform.inx:935: parser error : Opening and ending tag mismatch: main line 466 and div
  </div>
        ^
/usr/share/inkscape/extensions/applytransform.inx:938: parser error : Opening and ending tag mismatch: header line 127 and main
    </main>
           ^
/usr/share/inkscape/extensions/applytransform.inx:942: parser error : Opening and ending tag mismatch: body line 113 and div
  </div>
        ^
/usr/share/inkscape/extensions/applytransform.inx:948: parser error : Entity 'copy' not defined
      <li class="mr-3 mr-lg-0">&copy; 2020 GitHub, Inc.</li>
                                     ^
/usr/share/inkscape/extensions/applytransform.inx:998: parser error : Specification mandate value for attribute hidden
    >
    ^
/usr/share/inkscape/extensions/applytransform.inx:1000: parser error : Specification mandate value for attribute hidden
    <span class="js-stale-session-flash-signed-in" hidden>You signed in with ano
                                                         ^
/usr/share/inkscape/extensions/applytransform.inx:1001: parser error : Specification mandate value for attribute hidden
    <span class="js-stale-session-flash-signed-out" hidden>You signed out in ano
                                                          ^
/usr/share/inkscape/extensions/applytransform.inx:1004: parser error : Specification mandate value for attribute open
eset details-overlay details-overlay-dark lh-default text-gray-dark hx_rsm" open
                                                                               ^
/usr/share/inkscape/extensions/applytransform.inx:1007: parser error : Specification mandate value for attribute data-close-dialog
bsolute right-0 top-0" type="button" aria-label="Close dialog" data-close-dialog
                                                                               ^
/usr/share/inkscape/extensions/applytransform.inx:1021: parser error : Opening and ending tag mismatch: meta line 106 and body
  </body>
         ^
/usr/share/inkscape/extensions/applytransform.inx:1022: parser error : Opening and ending tag mismatch: link line 104 and html
</html>
       ^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 103

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 102

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 100

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 98

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 95

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 90

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 88

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 85

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 83

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 80

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 77

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 76

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 70

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 68

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 65

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 58

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 57

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 56

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 55

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 53

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 46

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 41

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 36

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 35

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 34

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 33

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 32

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 29

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 16

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 15

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 14

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 13

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 12

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 11

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag link line 10

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag meta line 9

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag head line 8

^
/usr/share/inkscape/extensions/applytransform.inx:1024: parser error : Premature end of data in tag html line 7

^
`

**Comment by Klowner** [comment]
Looks like you right-clicked the applytransform.inx from github and saved the HTML rather than the actual inx script.

**Comment by bad-blue-bull** [comment]
yes

**Comment by Klowner** [comment]
Download the raw file or use the download zip feature and unpack it from
there.
