### ISSUE TITLE
Extension crashes

### ISSUE THREAD

**Issue by jacekgajek** [Klowner/inkscape-applytransforms#30]
...with a message
`Traceback (most recent call last):
  File "applytransform.py", line 9, in <module>
    from inkex.paths import CubicSuperPath, Path
ImportError: No module named paths
`

**Comment by jacekgajek** [comment]
[yt_logo_mono_dark.svg.txt](https://github.com/Klowner/inkscape-applytransforms/files/5478271/yt_logo_mono_dark.svg.txt)

**Comment by jacekgajek** [comment]
I've used an old version of Inkscape. Upgrade fixed the issue

**Comment by Klowner** [comment]
Glad ya got it! I should probably add a big note on the README about inkscape versions and the different branches, amongst other things.

**Comment by jacekgajek** [comment]
The note is already there :) It's more about InkScape not your extension. Most software notifies about updates nowadays.
