### ISSUE TITLE
Errors when running

### ISSUE THREAD

**Issue by seancolsen** [Klowner/inkscape-applytransforms#35]
When I run, I get the following error:

```
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "applytransform.py", line 159, in <module>
    ApplyTransform().run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 140, in run
    self.save_raw(self.effect())
  File "applytransform.py", line 23, in effect
    self.recursiveFuseTransform(shape)
  File "applytransform.py", line 60, in recursiveFuseTransform
    transf = Transform(transf) * Transform(node.get("transform", None))
AttributeError: 'tuple' object has no attribute 'get'
```

I'm on:

- Inkscape 1.0.2 (1.0.2+r75+1)
- Ubuntu 20.04
- Python 3.8.5

Any advice? Thanks!

**Comment by seancolsen** [comment]
Yeah, as far as I can tell, I get the error no matter the file or the object selected.

Here's a zip (since GitHub won't let me upload svg directly) of an example file. [drawing.zip](https://github.com/Klowner/inkscape-applytransforms/files/6207128/drawing.zip) Open, select the rectangle. Choose "Extensions" > "Modify Path" > "Apply Transform".

**Comment by vmario89** [comment]
Hey,
the issue is the following line number 22 in this repo's code:

```
            for shape in self.svg.selected.items():
```

must be changed to

```
            for id, shape in self.svg.selected.items():
```

then it works properly.

**Comment by vmario89** [comment]
commit https://github.com/Klowner/inkscape-applytransforms/commit/aac7ddcd6c80239811928d09e0cb45b9417d1661 introduced that bug

**Comment by Klowner** [comment]
aye, that's the ticket, @vmario89 

should be good now, please re-open if the problem persists!
