### ISSUE TITLE
Is this works with Inkscape 0.92.5 ?

### ISSUE THREAD

**Issue by omidraha** [Klowner/inkscape-applytransforms#36]
Is this works with` Inkscape 0.92.5` ?
I can't see anything in `Modify Path` menu.

Info:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```
```
$ inkscape --version
Gtk-Message: 04:47:27.844: Failed to load module "atk-bridge"
Inkscape 0.92.5 (2060ec1f9f, 2020-04-08)
```

**Comment by Klowner** [comment]
The `master` branch is only compatible with Inkscape 1.0 onward. But you can download the `inkscape-pre1.0-compat` branch and that should still work fine with your version of Inkscape.

https://github.com/Klowner/inkscape-applytransforms/archive/refs/heads/inkscape-pre1.0-compat.zip
