### ISSUE TITLE
Does not seem to work for layer transform

### ISSUE THREAD

**Issue by X-Ryl669** [Klowner/inkscape-applytransforms#49]
Take a SVG file and delete some path in it. Then go to "Document properties" and click "Adjust page to drawing or selection". You'll get a transform on the layer itself that's not removed by this extension.

**Comment by vmario89** [comment]
hi. this is not a bug i think. please have a closer eye to what you select. if your selection is empty, automatically the whole document is parsed from root element down to all children. if you select sth. you might select only some path within a group or layer, so its parent's transform is kept.

**Comment by X-Ryl669** [comment]
That's it! Thanks.
