### ISSUE TITLE
applytransform.py:60

### ISSUE THREAD

**Issue by Vitalicus** [Klowner/inkscape-applytransforms#55]
I recive a error in new version of inskape
`applytransform.py:60: DeprecationWarning: inkex.deprecated.main.transform_mul -> Use @ operator instead
  transf = Transform(transf) * Transform(node.get("transform", None))
`
What to change?

**Comment by Klowner** [comment]
Looks like Python is adding a dedicated infix operator for matrix multiplication https://peps.python.org/pep-0465/

**Comment by Klowner** [comment]
The message you reported is just a deprecation warning, meaning the `*`
should still work.

Are you receiving an actual error? What is it you are trying to do?

**Comment by Vitalicus** [comment]
It work. Thanks for solution!
