### ISSUE TITLE
Negative values

### ISSUE THREAD

**Issue by imabot2** [Klowner/inkscape-applytransforms#57]
Hi, have a look at the attached image. When applying tranforms, I still get negative values:

`m 500,200 c -93.00056,0.77365 -176.95216,75.89244 -196.49192,165.35893 -7.66452,28.92451 -5.36465,68.21355 27.02966,80.71182 32.7893,15.50741 73.39068,-14.23091 69.60155,-50.04238 5.97407,-50.33489 52.37777,-95.71901 103.83234,-95.88908 55.97802,6.45339 106.34526,64.06624 94.11814,121.42401 -12.01567,34.77315 -43.45207,57.47053 -67.87036,83.44066 -70.75545,68.78515 -137.95665,141.53976 -198.30828,219.63323 ...`

Here is the preview in another app:
![image](https://user-images.githubusercontent.com/33400146/193409977-83982ffc-86a0-4760-b17f-de6a2e8a4253.png)

But image is still fine in InkScape. Did I miss something or is it a bug?

![tmp](https://user-images.githubusercontent.com/33400146/193409836-f8c9cd0d-7af9-4eb0-a86d-0f801c9927c6.svg)

**Comment by imabot2** [comment]
The problem was not the extension. Sorry.

**Comment by Klowner** [comment]
No worries!
