### ISSUE TITLE
DeprecationWarning: inkex.deprecated.main.transform_mul

### ISSUE THREAD

**Issue by imabot2** [Klowner/inkscape-applytransforms#58]
I try the extension on Inkscape 1.2.1, I've got the following error. 
```
applytransform.py:60: DeprecationWarning: inkex.deprecated.main.transform_mul -> Use @ operator instead
  transf = Transform(transf) * Transform(node.get("transform", None))
```

I found the line in the Python script, but I'm not sure how to update the code.

**Comment by Klowner** [comment]
That's not an error, just a deprecation warning. 

Python now uses an `@` for matrix multiplication.

**Comment by imabot2** [comment]
Thank you, I try this, but it didn't solve my problem

 transf = Transform(transf) @ Transform(node.get("transform", None))

**Comment by Klowner** [comment]
Duplicate of #55
