### ISSUE TITLE
 can't find '__main__' module in 'C:\\Program Files\\Inkscape\\bin'

### ISSUE THREAD

**Issue by PlopTheReal** [Klowner/inkscape-applytransforms#61]
Getting the following error when running the plugin: 
C:\Program Files\Inkscape\bin\pythonw.exe: can't find '__main__' module in 'C:\\Program Files\\Inkscape\\bin'

Inkscape 1.2.2 (732a01da63, 2022-12-09)

**Comment by Klowner** [comment]
Sounds like a more general problem than something related specifically to this extension.

Do other extensions work?

Similar issue here solved by reinstalling:
https://inkscape.org/forums/questions/inkscape-extensions-not-working/

**Comment by PlopTheReal** [comment]
yes thanks, interestingly reinstalling did the job..
