### ISSUE TITLE
Does not work for me at all

### ISSUE THREAD

**Issue by rulatir** [Klowner/inkscape-applytransforms#7]
This extension does not work for me. It simply removes the `transform` attribute from the `<polyline>` element, but does **not** apply the transform to the data in the `points` attribute.

**Comment by Klowner** [comment]
Please include some sort of information that can help me fix the issue: Inkscape version, OS, a sample svg, etc.

**Comment by Klowner** [comment]
@rulatir could you test with @jdugge 's fix? Please re-open this ticket if you're still having issues.
